### ISSUE TITLE
[Bug] ZQMStream Error when setting up qudi from scratch

### ISSUE THREAD

**Issue by kay-jahnke** [Ulm-IQO/qudi-core#43] opened 2023-01-16 12:45 UTC
### Version

Development

### What is affected by the bug?

When I set up qudi from scratch on pure python 3.9.13 I get a ZQMStream Error .
Interestingly, the behaviour of the console (which runs as an ipython kernel) seems not to be affected.

### When does the bug occur?

When starting qudi without any module. not even a config needs to be loaded.
Hence I suspect the IPython kernel connection to be the culprit.

### How do we replicate the issue?

Pure python 3.9.13 on Windows 10 Pro 22H2 with AMD Ryzen 7 PRO 5850U

Package                       Version       Editable project location
----------------------------- ------------- -------------------------------------
anyio                         3.6.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asteval                       0.9.28
asttokens                     2.2.1
attrs                         22.2.0
backcall                      0.2.0
beautifulsoup4                4.11.1
bleach                        5.0.1
bronkhorst-propar             1.0.1
certifi                       2022.12.7
cffi                          1.15.1
charset-normalizer            3.0.1
colorama                      0.4.6
comm                          0.1.2
contourpy                     1.0.7
cycler                        0.11.0
debugpy                       1.6.5
decorator                     5.1.1
defusedxml                    0.7.1
entrypoints                   0.4
executing                     1.2.0
fastjsonschema                2.16.2
fonttools                     4.38.0
fqdn                          1.5.1
future                        0.18.3
fysom                         2.1.6
gitdb                         4.0.10
GitPython                     3.1.30
idna                          3.4
importlib-metadata            6.0.0
ipykernel                     6.20.1
ipython                       8.8.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
isoduration                   20.11.0
jedi                          0.18.2
Jinja2                        3.1.2
jsonpointer                   2.3
jsonschema                    4.17.3
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.4.4
jupyter_core                  5.1.3
jupyter-events                0.6.3
jupyter_server                2.1.0
jupyter_server_terminals      0.4.4
jupyterlab-pygments           0.2.2
jupyterlab-widgets            3.0.5
jupytext                      1.14.4
kiwisolver                    1.4.4
lmfit                         1.1.0
lxml                          4.9.2
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib                    3.6.3
matplotlib-inline             0.1.6
mdit-py-plugins               0.3.3
mdurl                         0.1.2
mistune                       2.0.4
nbclassic                     0.4.8
nbclient                      0.7.2
nbconvert                     7.2.7
nbformat                      5.7.3
nest-asyncio                  1.5.6
nidaqmx                       0.5.7
nmrglue                       0.9
notebook                      6.5.2
notebook_shim                 0.2.2
numpy                         1.24.1
packaging                     23.0
pandocfilters                 1.5.0
parso                         0.8.3
Phidget22                     1.13.20230109
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           22.3.1
platformdirs                  2.6.2
plumbum                       1.8.1
prometheus-client             0.15.0
prompt-toolkit                3.0.36
protobuf                      4.21.12
psutil                        5.9.4
pure-eval                     0.2.2
pycparser                     2.21
pyFirmata                     1.1.0
Pygments                      2.14.0
pyparsing                     3.0.9
pyqtgraph                     0.13.1
pyrsistent                    0.19.3
pyserial                      3.5
PySide2                       5.15.2
python-dateutil               2.8.2
python-json-logger            2.0.4
PyVISA                        1.13.0
pywin32                       305
pywinpty                      2.0.10
PyYAML                        6.0
pyzmq                         25.0.0
qtconsole                     5.4.0
QtPy                          2.3.0
qudi-core                     1.3.1.dev0    C:\Software\qudi\qudi-core
qudi-iqo-modules              0.4.1.dev0    C:\Software\qudi\qudi-iqo-modules
qudi-nvision-modules          0.1.1         C:\Software\qudi\qudi-nvision-modules
requests                      2.28.2
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rpyc                          5.3.0
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.7
Rx                            3.2.0
scipy                         1.10.0
Send2Trash                    1.8.0
setuptools                    58.1.0
shiboken2                     5.15.2
six                           1.16.0
smmap                         5.0.0
sniffio                       1.3.0
soupsieve                     2.3.2.post1
stack-data                    0.6.2
terminado                     0.17.1
tinycss2                      1.2.1
toml                          0.10.2
tornado                       6.2
traitlets                     5.8.1
typing_extensions             4.4.0
uncertainties                 3.1.7
uri-template                  1.2.0
urllib3                       1.26.14
wcwidth                       0.2.6
webcolors                     1.12
webencodings                  0.5.1
websocket-client              1.4.2
wheel                         0.38.4
widgetsnbextension            4.0.5
zaber-motion                  2.15.3
zaber-motion-bindings-windows 2.15.3
zipp                          3.11.0

### Expected behavior

start qudi without throwing errors.

### Relevant log output

```shell
C:\Software\python-environments\qudi\Scripts\python.exe C:\Software\qudi\qudi-core\src\qudi\runnable.py --debug 
> Starting qudi in debug mode...
> Applying configuration from "C:/Software/qudi/qudi-nvision-modules/src/qudi/config/hardware_test/temperature_test.cfg"...
> Qudi configuration complete!
> Activating main GUI module...
C:\Software\python-environments\qudi\lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.
                
  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)

C:\Software\python-environments\qudi\lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.SUB, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.
                
  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)

> Initialization complete! Starting Qt event loop...
>
```

**Comment by kay-jahnke** [comment] 2023-01-16 12:48
Additionally, when shutting down qudi, I get an access violation:
```
Windows fatal exception: access violation

Current thread 0x00000328 (most recent call first):
  File "C:\Software\python-environments\qudi\lib\site-packages\zmq\sugar\socket.py", line 179 in __del__
Unexpected return value 3221225477. Exiting.

Process finished with exit code -1

```

I do not get this access violation if I just "Restart" qudi.

**Comment by Neverhorst** [comment] 2023-01-16 15:09
Thank you. 
Apparently `pyzmq 25.0.0` has been released and brought some breaking changes that are not accounted for by one of the `jupyter` packages or `qtconsole`. qudi does not list `pyzmq` as dependency and the dependency tree reveals those two packages as the ones depending on `pyzmq`.
In hopes that either one of these projects will fix the issue in the future, I recommend downgrading to `pyzmq < 25.0.0`.

The log output you posted are just user warnings and no errors but the access violation in the end is caused by the same issue and that's bad.

**Comment by Neverhorst** [comment] 2023-10-30 14:41
Seems to have been fixed by the jupyter project by now.

**Closed by Neverhorst** 2023-10-30 14:41 UTC
Labels: bug
